### ISSUE TITLE
Use YAML Tags for Metadata and Function-Invocations

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zs-yaml#1]
Currently, the `zs-yaml` package uses nodes such as `_meta`, `_f`, and `_a` to handle metadata, functions, and arguments in YAML files. This can be streamlined and made more readable by utilizing YAML tags instead.

**Example:**

Given the current YAML structure:

```yaml
# 1) Metadata is used to specify the type needed for
#    (de-)serialization and custom transform functions
# 2) User are free to use their preferred date format
#    for the birth data as the a normalization function
#    get invoked.
# 3) Yaml allows avoiding clutter and adding comments
#    like this one :)

_meta:
  schema_module: person.api
  schema_type: Person
  transformation_module: "./transformations.py"

name: John Doe

birthdate:
  _f: normalize_date
  _a: "01/01/1990"
birth_location: Springfield, USA

current_job: Software Engineer
income: 75000

experience:
  - role: Intern
    years: 1
  - role: Junior Developer
    years: 2
  - role: Senior Developer
    years: 3
```

We propose converting this to use YAML tags as follows, encapsulating metadata within a single tag:

```yaml
# 1) Metadata is used to specify the type needed for
#    (de-)serialization and custom transform functions
# 2) User are free to use their preferred date format
#    for the birth data as the a normalization function
#    get invoked.
# 3) Yaml allows avoiding clutter and adding comments
#    like this one :)

!metadata
metadata:
  schema_module: person.api
  schema_type: Person
  transformation_module: "./transformations.py"

name: John Doe

birthdate: !normalize_date "01/01/1990"
birth_location: Springfield, USA

current_job: Software Engineer
income: 75000

experience:
  - role: Intern
    years: 1
  - role: Junior Developer
    years: 2
  - role: Senior Developer
    years: 3
```

**Advantages:**
1. **Readability:** Using tags makes the YAML file more readable and less cluttered.
2. **Clarity:** Tags clearly indicate special handling or transformations.
3. **Consistency:** Standardizing on tags can help maintain consistency across different YAML files and projects.
