### ISSUE TITLE
`insert_yaml` functions overwrites other nodes.

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zs-yaml#12]
Currently the `insert_yaml` function variants replace all nodes on the same level - e.g. have a look at this yaml file:

```yaml
_meta:
  schema_module: myschema.api
  schema_type: SomeTye

_f: insert_yaml
_a: 
  _file: someother.yaml

additionalNode:
  someValue: 5
```

When using `zs-yaml my.yaml my.rendered.yaml` I can see that the `additionalNode` is gone.
