### ISSUE TITLE
Basic tempalte support for `insert_yaml` and `insert_yaml_as_extern`

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zs-yaml#4]
Instead of only directly inserting the transformed content, these functions should also support templates - e.g. if multiple instances only differ in a small amount of field this could allow something like:

```yaml
mynode:
  _f: insert_yaml
  _a: 
     file: 'cube_template.yaml'
     template_args:
        scale: 2.0
        color: blue
```

This solution should stay compatible to the old invocation which allowed to specify a file path without using the template functionality. E.g. 

```yaml
mynode:
  _f: insert_yaml
  _a: 'cube1.yaml'
```
